name: reachify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^9.0.0
  change_app_package_name: ^1.5.0
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  video_player: ^2.9.1
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_slidable: ^3.1.1
  percent_indicator: ^4.2.3
  http: ^1.2.2
  stability_image_generation: ^0.0.4
  syncfusion_flutter_charts: ^27.1.55
  swipeable_button_view: ^0.0.2
  provider: ^6.1.2
  dotted_line: ^3.2.3
  animate_do: ^3.3.4
  fl_chart: ^0.69.0
  flutter_cached_pdfview: ^0.4.3
  gap: ^3.0.1
  file_picker: ^8.1.4
  flutter_spinkit: ^5.2.1
  dotted_border: ^2.1.0
  card_swiper: ^3.0.1
  syncfusion_flutter_gauges: ^27.2.5
  ionicons: ^0.2.2
  flutter_iconly: ^1.0.2
  badges: ^3.1.2
  easy_stepper: ^0.8.5+1
  bottom_navy_bar: ^6.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/welcome/recOne.png
    - assets/welcome/recTwo.png
    - assets/welcome/recThree.png
    - assets/welcome/growing.png
    - assets/auth/signIn.png
    - assets/auth/authImg.png
    - assets/auth/logo/deardevil.jpg
    - assets/cinema/
    - assets/coffee/
    - assets/food-delivery/product/
    - assets/food-delivery/
    - assets/food-delivery/icon/
    - assets/grocery/
    - assets/football/
    - assets/plant-shop/
    - assets/food-recipe/
    - assets/banking-app/
    - assets/doctor-appoinment/
    - assets/food-delivery(foodel)/
    - assets/food-delivery(foodel)/ramen/
    - assets/food-delivery(foodel)/burger/
    - assets/dashoboard/
    - assets/pdf/
    - assets/coffee-shop/
    - assets/fashion/
    - assets/fashion/category_image/
    - assets/fashion/category_image/sub_category/
    - assets/img/
    - assets/health/
    - assets/educational-app/
    - assets/agriplant/
    - assets/grocery-ui/
    - assets/job-finder/
